Repository fajrinasah/dnt, pull requests merged in 2023-08, with the labels that each got.

#8 Draft: K1 37 manage cashier
  package-lock.json
  package.json
  src/App.js
  src/components/01-atoms/forAuthAndManage/buttons/ButtonStandard/index.jsx
  src/components/01-atoms/forAuthAndManage/inputs/formInputs/InputPassword/index.jsx
  src/components/01-atoms/forAuthAndManage/inputs/formInputs/InputText/index.jsx
  src/components/01-atoms/forAuthAndManage/inputs/toolbarInputs/InputToolbarSearch/index.jsx
  src/components/01-atoms/forAuthAndManage/inputs/toolbarInputs/InputToolbarSelect/index.jsx
  src/components/01-atoms/forAuthAndManage/inputs/toolbarInputs/InputToolbarSort/index.jsx
  src/components/02-molecules/forAuthAndManage/forms/cashiers/FormAddCashier/index.jsx
  src/components/02-molecules/forAuthAndManage/forms/cashiers/FormAddCashier/styles.css
  src/components/02-molecules/forAuthAndManage/forms/cashiers/FormEditEmailCashier/index.jsx
  src/components/02-molecules/forAuthAndManage/forms/cashiers/FormEditEmailCashier/styles.css
  src/components/02-molecules/forAuthAndManage/tableRows/manageCashiersTableRow/index.jsx
  src/components/02-molecules/forAuthAndManage/tableRows/manageCashiersTableRow/styles.css
  src/components/02-molecules/forAuthAndManage/toolbars/ManageCashiersProductsToolbars/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/ModalChangePhotoProfile/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/ModalChangePhotoProfile/styles.css
  src/components/03-organisms/forAuthAndManage/modals/ModalConfirmation/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/ModalConfirmation/styles.css
  src/components/03-organisms/forAuthAndManage/modals/cashiers/ModalAddCashier/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/cashiers/ModalAddCashier/styles.css
  src/components/03-organisms/forAuthAndManage/modals/cashiers/ModalEditCashier/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/cashiers/ModalEditCashier/styles.css
  src/components/03-organisms/forAuthAndManage/modals/confirmationModal/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/confirmationModal/styles.css
  src/components/03-organisms/forAuthAndManage/modals/styles.css
  src/components/03-organisms/forAuthAndManage/tables/TableCashiers/index.jsx
  src/components/04-templates/forAuthAndManage/TempHome/index.jsx
  src/components/05-pages/forAuthAndManage/PageManageCashiers/index.jsx
  src/components/05-pages/forAuthAndManage/PageManageCashiers/styles.css
  src/helpers/aesEncryption.js
  src/helpers/hashEncryption.js
  src/helpers/index.js
  src/helpers/queries/cashiers.js
  src/store/slices/auth/thunks/index.js
  src/store/slices/manageCashiers/thunks/index.js
  src/validationSchemata/addCashierValidationSchema.js
  src/validationSchemata/index.js
Labels: enhancement

#9 K1 33 cashier can create transaction
  package-lock.json
  package.json
  src/App.js
  src/components/01-atoms/CreateTransactions/QuantityStepper/index.jsx
  src/components/01-atoms/CreateTransactions/QuantityStepper/styles.css
  src/components/01-atoms/index.js
  src/components/02-molecules/CreateTransactions/Filter/index.jsx
  src/components/02-molecules/CreateTransactions/Filter/styles.css
  src/components/02-molecules/CreateTransactions/QuantityStepper/index.jsx
  src/components/02-molecules/CreateTransactions/QuantityStepper/styles.css
  src/components/02-molecules/CreateTransactions/Search/index.jsx
  src/components/02-molecules/CreateTransactions/Search/styles.css
  src/components/02-molecules/index.js
  src/components/03-organisms/CreateTransactions/CardProduct/index.jsx
  src/components/03-organisms/CreateTransactions/CardProduct/styles.css
  src/components/03-organisms/CreateTransactions/CardProductSkeleton/index.jsx
  src/components/03-organisms/CreateTransactions/CardProductSkeleton/styles.css
  src/components/03-organisms/index.js
  src/components/04-templates/CreateTransactions/ProductList/index.jsx
  src/components/04-templates/CreateTransactions/ProductList/styles.css
  src/components/05-pages/CreateTransactions/index.jsx
  src/components/05-pages/CreateTransactions/styles.css
  src/components/05-pages/forAuthAndManage/index.js
  src/components/05-pages/index.js
  src/store/index.js
  src/store/slices/manageCategories/thunks/index.js
  src/store/slices/manageProducts/thunks/index.js
  src/store/slices/transactions/index.js
  src/store/slices/transactions/thunks/index.js
  tailwind.config.js
Labels: bug, enhancement

#11 K1 29 admin can create and modify category
  src/App.js
  src/components/02-molecules/forAuthAndManage/forms/categories/FormAddCategory/index.jsx
  src/components/02-molecules/forAuthAndManage/forms/categories/FormAddCategory/styles.css
  src/components/02-molecules/forAuthAndManage/forms/categories/FormEditNameCategory/index.jsx
  src/components/02-molecules/forAuthAndManage/forms/categories/FormEditNameCategory/styles.css
  src/components/02-molecules/forAuthAndManage/toolbars/ManageCategoriesToolbars/index.jsx
  src/components/02-molecules/forAuthAndManage/toolbars/ManageCategoriesToolbars/styles.css
  src/components/03-organisms/forAuthAndManage/modals/categories/ModalAddCategory/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/categories/ModalAddCategory/styles.css
  src/components/03-organisms/forAuthAndManage/modals/categories/ModalEditNameCategory/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/categories/ModalEditNameCategory/styles.css
  src/components/03-organisms/forAuthAndManage/modals/categories/categoryAddModal/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/categories/categoryEditModal/index.jsx
  src/components/03-organisms/forAuthAndManage/modals/categories/categoryEditModal/styles.css
  src/components/03-organisms/forAuthAndManage/tables/TableCategories/index.jsx
  src/components/03-organisms/forAuthAndManage/tables/TableProducts/index.jsx
  src/components/05-pages/forAuthAndManage/PageManageCashiers/index.jsx
  src/components/05-pages/forAuthAndManage/PageManageCategories/index.jsx
  src/components/05-pages/forAuthAndManage/PageManageCategories/styles.css
  src/helpers/index.js
  src/helpers/queries/categories.js
  src/store/slices/manageCategories/thunks/index.js
  src/validationSchemata/categoryValidationSchema.js
  src/validationSchemata/index.js
Labels: enhancement

#13 K1 58 fix css conflict with tailwind
  src/App.css
  src/components/01-atoms/forAuthAndManage/buttons/ButtonHelp/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/formInputs/CheckboxShowPassword/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/formInputs/InputConfirmPassword/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/formInputs/InputFileCustom/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/formInputs/InputPassword/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/formInputs/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/toolbarInputs/InputToolbarSearch/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/toolbarInputs/InputToolbarSelect/styles.css
  src/components/01-atoms/forAuthAndManage/inputs/toolbarInputs/InputToolbarSort/styles.css
  src/components/02-molecules/forAuthAndManage/forms/auth/FormLogin/styles.css
  src/components/02-molecules/forAuthAndManage/forms/cashiers/FormAddCashier/styles.css
  src/components/02-molecules/forAuthAndManage/manageCashiersProductsPagination/index.jsx
  src/components/02-molecules/forAuthAndManage/tableRows/manageCashiersTableRow/styles.css
  src/components/02-molecules/forAuthAndManage/tableRows/manageCategoriesAndProductsTableRow/styles.css
  src/components/02-molecules/forAuthAndManage/toolbars/ManageCashiersProductsToolbars/index.jsx
  src/components/02-molecules/forAuthAndManage/toolbars/ManageCashiersProductsToolbars/styles.css
  src/components/02-molecules/forAuthAndManage/toolbars/ManageCategoriesToolbars/index.jsx
  src/components/02-molecules/forAuthAndManage/toolbars/ManageCategoriesToolbars/styles.css
  src/components/02-molecules/forAuthAndManage/toolbars/ManageProductsToolbars/index.jsx
  src/components/02-molecules/forAuthAndManage/toolbars/ManageProductsToolbars/styles.css
  src/components/02-molecules/forAuthAndManage/toolbars/styles.css
  src/components/05-pages/forAuthAndManage/PageManageCashiers/index.jsx
  src/components/05-pages/forAuthAndManage/PageManageCashiers/styles.css
  src/components/05-pages/forAuthAndManage/PageManageCategories/index.jsx
  src/components/05-pages/forAuthAndManage/PageManageCategories/styles.css
  src/components/05-pages/forAuthAndManage/PageManageProducts/index.jsx
Labels: bug

#14 CREATE: all files related to reports
  package-lock.json
  package.json
  src/App.js
  src/components/05-pages/CreateTransactions/index.jsx
  src/components/05-pages/Reports/ProductSold/index.jsx
  src/components/05-pages/Reports/ProductSold/styles.css
  src/components/05-pages/Reports/SalesAggregates/index.jsx
  src/components/05-pages/Reports/SalesAggregates/styles.css
  src/components/05-pages/Reports/SalesReports/index.jsx
  src/components/05-pages/Reports/SalesReports/styles.css
  src/helpers/formatCurrency.js
  src/store/index.js
  src/store/slices/manageProducts/thunks/index.js
  src/store/slices/reports/index.js
  src/store/slices/reports/thunks/index.js
Labels: enhancement
